POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name": "dave",
    "email": "dave@gmail.com",
    "password": "12345"
}


###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "dave@gmail.com",
    "password": "12345"
}

###
GET http://localhost:5000/api/products/


###
GET http://localhost:5000/api/products/my-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWQyYTYzOTk1Y2JkY2QxNTM2Mzc2MSIsImlhdCI6MTY3MzE0MDUzMywiZXhwIjoxNjc1NzMyNTMzfQ.Tm26ca6a5qeR2nvsfs-nfoh16hOmUrswwKXPQOjJq9A


###
PUT http://localhost:5000/api/products/update-product/63b85c7e1bf46564d6043f5f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWQyYTYzOTk1Y2JkY2QxNTM2Mzc2MSIsImlhdCI6MTY3MzE0MDUzMywiZXhwIjoxNjc1NzMyNTMzfQ.Tm26ca6a5qeR2nvsfs-nfoh16hOmUrswwKXPQOjJq9A

{
    "title": "updated"
}


###
DELETE  http://localhost:5000/api/products/delete-product/63ba2b317d1f5135cb44e36f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWQyYTYzOTk1Y2JkY2QxNTM2Mzc2MSIsImlhdCI6MTY3MzE0MDUzMywiZXhwIjoxNjc1NzMyNTMzfQ.Tm26ca6a5qeR2nvsfs-nfoh16hOmUrswwKXPQOjJq9A

